Repository projectdysnomia/dysnomia, pull requests merged in 2023-01, with the labels that each got.

#20 docs: document audit log after parameter
  index.d.ts
  lib/Client.js
  lib/structures/Guild.js
Labels: documentation

#22 feat: add new message types
  index.d.ts
  lib/Constants.js
  lib/structures/Message.js
Labels: documentation, enhancement

#24 feat: add GIF as a supported sticker format
  index.d.ts
  lib/Constants.js
Labels: enhancement

#21 feat: role subscriptions
  index.d.ts
  lib/Constants.js
  lib/structures/Message.js
  lib/structures/Role.js
Labels: enhancement

#28 feat(Client): add threadID support to editWebhookMessage
  index.d.ts
  lib/Client.js
  lib/structures/Message.js
Labels: enhancement
