Repository projectdysnomia/dysnomia, pull requests merged in 2023-02, with the labels that each got.

#29 fix(ShardManager): emit properly to client
  lib/gateway/ShardManager.js
Labels: bug

#32 fix(ShardManager): add requestTimeout default
  lib/gateway/ShardManager.js
Labels: bug

#26 chore: housekeeping
  .github/workflows/pr.yml
  README.md
  esm.mjs
  examples/applicationCommands.js
  examples/basicCommands.js
  examples/components.js
  examples/embed.js
  examples/intent.js
  examples/pingpong.js
  examples/playFile.js
  examples/reactionButtons.js
  examples/sharding.js
  index.d.ts
  index.js
  lib/Client.js
  lib/Constants.js
  lib/gateway/Shard.js
  lib/rest/Endpoints.js
  lib/structures/AutoModerationRule.js
  lib/structures/Guild.js
  lib/structures/GuildAuditLogEntry.js
  lib/structures/GuildChannel.js
  lib/structures/GuildIntegration.js
  lib/structures/GuildPreview.js
  lib/structures/GuildScheduledEvent.js
  lib/structures/Invite.js
  lib/structures/Member.js
  lib/structures/Message.js
  lib/structures/StageChannel.js
  lib/structures/StageInstance.js
  lib/structures/TextChannel.js
  lib/structures/VoiceChannel.js
  lib/util/emitDeprecation.js
Labels: documentation, enhancement

#34 types(AutoModerationActionMetadata): add `custom_message` property
  index.d.ts
Labels: enhancement
