Repository projectdysnomia/dysnomia, pull requests merged in 2023-07, with the labels that each got.

#78 Added port option to rest options
  index.d.ts
  lib/Client.js
  lib/rest/RequestHandler.js
Labels: type: enhancement, scope: REST

#79 feat: add headers to REST options
  index.d.ts
  lib/Client.js
  lib/rest/RequestHandler.js
Labels: type: enhancement, scope: REST

#80 types: RequestHandlerOptions#port should be a number
  index.d.ts
Labels: type: bug, scope: typings, type: farming

#82 docs(Client): remove missing options.maxShards option
  lib/Client.js
Labels: type: docs

#83 types(PartialEmoji): make `id` optional
  index.d.ts
Labels: type: docs

#84 feat(Client,Guild): add `defaultForumLayout` to createChannel()
  index.d.ts
  lib/Client.js
  lib/structures/Guild.js
Labels: type: enhancement, scope: REST, reason: Discord

#85 feat: support role flags
  index.d.ts
  lib/Constants.js
  lib/gateway/Shard.js
  lib/structures/Role.js
Labels: type: enhancement, reason: Discord, scope: structures

#88 feat(Client): support `with_counts` parameter in getRESTGuilds()
  index.d.ts
  lib/Client.js
Labels: type: enhancement, scope: REST, reason: Discord

#69 feat: support onboarding updates
  index.d.ts
  lib/Client.js
  lib/Constants.js
  lib/structures/Guild.js
Labels: type: enhancement, scope: REST, scope: typings, reason: Discord

#86 feat: support attachment flags
  index.d.ts
  lib/Constants.js
  lib/structures/Attachment.js
Labels: type: enhancement, reason: Discord, scope: structures

#89 types(Client): make `editChannelOptions()` channel position optional
  index.d.ts
  lib/Client.js
  lib/structures/Guild.js
Labels: scope: typings, reason: Discord, type: farming

#87 feat: support `message_author_id` on uncached `MESSAGE_REACTION_ADD` payloads
  index.d.ts
  lib/gateway/Shard.js
Labels: type: enhancement, scope: gateway, reason: Discord

#92 fix(types): allow attachment command options in createCommand() and co.
  index.d.ts
Labels: type: bug, scope: typings

#90 feat: add `Client#getApplication()`
  index.d.ts
  lib/Client.js
  lib/rest/Endpoints.js
Labels: type: enhancement, scope: REST, scope: typings, reason: Discord
