Repository projectdysnomia/dysnomia, pull requests merged in 2023-10, with the labels that each got.

#117 feat(Client): add `guildScheduledEventID` to `createStageInstance`
  index.d.ts
  lib/Client.js
  lib/structures/StageChannel.js
Labels: type: enhancement, scope: REST, reason: Discord

#119 fix(Client): wrong request url in editGuildWidget
  lib/Client.js
Labels: type: bug, scope: REST

#121 fix(Shard): wrong options used in shard
  lib/gateway/Shard.js
Labels: type: bug, scope: gateway
