Repository projectdysnomia/dysnomia, pull requests merged in 2023-03, with the labels that each got.

#38 fix(VoiceConnection): Use 74 bytes for UDP discovery
  lib/voice/VoiceConnection.js
Labels: bug

#40 chore: set version to 0.2.0-dev, remove deprecated APIs
  esm.mjs
  examples/basicCommands.js
  examples/reactionButtons.js
  index.d.ts
  index.js
  lib/Client.js
  lib/Constants.js
  lib/command/Command.js
  lib/command/CommandClient.js
  lib/structures/AutoModerationRule.js
  lib/structures/CommandInteraction.js
  lib/structures/ComponentInteraction.js
  lib/structures/Guild.js
  lib/structures/Message.js
  lib/structures/ModalSubmitInteraction.js
  lib/structures/PrivateChannel.js
  lib/structures/TextChannel.js
  lib/structures/TextVoiceChannel.js
  lib/structures/ThreadChannel.js
  lib/util/emitDeprecation.js
  package.json
Labels: type: enhancement, scope: gateway, scope: REST, scope: meta, scope: typings

#42 fix(Interaction): return default Interaction class on unknown interaction types
  lib/structures/Interaction.js
Labels: type: bug

#43 fix(Interaction): return default Interaction class on unknown interaction types (v0.1.x)
  lib/structures/Interaction.js
Labels: type: bug

#47 chore(examples/components): fix typo, update component type
  examples/components.js
Labels: type: enhancement, scope: meta

#49 fix(Channel, Message): update removed constants
  lib/structures/Channel.js
  lib/structures/Message.js
Labels: type: bug

#51 feat(Guild): support addGuildMember
  index.d.ts
  lib/Client.js
  lib/structures/Guild.js
Labels: type: enhancement, scope: REST, reason: Discord

#53 fix(PrivateThreadChannel): properly propagate updates
  lib/structures/PrivateThreadChannel.js
Labels: type: bug, scope: gateway, type: farming

#54 fix(PrivateThreadChannel): properly propagate updates (v0.1.x backport)
  lib/structures/PrivateThreadChannel.js
Labels: type: bug, scope: gateway, type: farming

#55 feat(Client): add missing properties to old guild object
  index.d.ts
  lib/gateway/Shard.js
Labels: type: enhancement, scope: gateway, scope: typings
