Repository projectdysnomia/dysnomia, pull requests merged in 2023-08, with the labels that each got.

#97 fix(types): add ModalSubmitInteraction to AnyInteractionGateway
  index.d.ts
Labels: type: bug, scope: typings

#98 types: correct gateway/REST versions in Constants interface
  index.d.ts
Labels: scope: typings

#99 fix(Attachment): include `flags` in toJSON() output
  lib/structures/Attachment.js
Labels: type: farming, scope: structures

#96 feat: support GUILD_MEDIA channels
  esm.mjs
  index.d.ts
  index.js
  lib/Client.js
  lib/Constants.js
  lib/gateway/Shard.js
  lib/structures/Channel.js
  lib/structures/ForumChannel.js
  lib/structures/GuildChannel.js
  lib/structures/MediaChannel.js
  lib/structures/PublicThreadChannel.js
Labels: type: enhancement, help wanted, scope: gateway, reason: Discord, scope: structures

#101 feat: document being able to set activity state
  index.d.ts
  lib/Client.js
  lib/gateway/Shard.js
Labels: type: docs, scope: typings, reason: Discord

#103 hotfix(Role): include `flags` in toJSON() output
  lib/structures/Role.js
Labels: type: bug, type: farming, scope: structures

#104 hotfix(Role): include `flags` in toJSON() output (v0.1.x)
  lib/structures/Role.js
Labels: type: bug, type: farming, scope: structures

#105 hotfix(Shard): remove nullish coalesce
  lib/gateway/Shard.js
Labels: type: bug, type: farming

#100 chore: set package.json version to 0.1.3
  package.json
Labels: scope: meta
