Repository projectdysnomia/dysnomia, pull requests merged in 2025-08, with the labels that each got.

#208 feat(voice): handle 4021 and 4022 close codes
  lib/voice/VoiceConnection.js
Labels: scope: voice, reason: Discord

#219 feat: add pin messages permission
  index.d.ts
  lib/Constants.js
Labels: type: enhancement, scope: meta, reason: Discord

#216 feat: support selects in modals
  index.d.ts
  lib/Constants.js
Labels: type: enhancement, scope: typings, reason: Discord
