Repository projectdysnomia/dysnomia, pull requests merged in 2025-04, with the labels that each got.

#194 feat: support components v2
  examples/components-v2.js
  index.d.ts
  lib/Client.js
  lib/Constants.js
  lib/structures/Message.js
Labels: type: enhancement, scope: REST, scope: typings, reason: Discord

#199 types(UnfurledMediaItem): add response-only properties
  index.d.ts
Labels: scope: typings, type: farming

#201 fix(types): widen the `AnyChannel` type to cover all channel types
  index.d.ts
Labels: type: bug, scope: typings

#198 chore: set package version to 0.2.3
  package.json
Labels: scope: meta
